### ISSUE TITLE
[LINE Channel] How to get sender id in group?

### ISSUE THREAD

**Issue by fuine6** [microsoft/BotFramework-Services#152] opened 2019-12-04 08:35 UTC
This is what i found in ngrok, I can't seem to get sender id.
```
{
    "type": "message",
    "id": "a835c1b9017f4861bc28ee6eb48ac5f9",
    "timestamp": "2019-12-04T06:53:04.6195542Z",
    "serviceUrl": "https://line.botframework.com/",
    "channelId": "line",
    "from": {
        "id": "C7512d5c526df82ce8aa0ddxxxxxxxxxx", // <- group id.
        "name": "LINE"
    },
    "conversation": {
        "isGroup": false,
        "id": "C7512d5c526df82ce8aa0ddxxxxxxxxxx|Iegtzf7rAtF"
    },
    "recipient": {
        "id": "Iegtzf7rAtF",
        "name": "thebot-test"
    },
    "text": "test"
}
```

But I can get it from the [reference](https://developers.line.biz/en/reference/messaging-api/#source-group).
```
{
    "events": [
        {
            "type": "message",
            "replyToken": "26c8475686bd49bd8e86d0xxxxxxxxxx",
            "source": {
                "userId": "U46eb74ae1dd9cd8772bb63xxxxxxxxxx", // <- This is what i need.
                "groupId": "C7512d5c526df82ce8aa0ddxxxxxxxxxx",
                "type": "group"
            },
            "timestamp": 1575441507877,
            "message": {
                "type": "text",
                "id": "11027712178895",
                "text": "test"
            }
        }
    ],
    "destination": "U76c146a68974eae44b20ebxxxxxxxxxx"
}
```
In bot framework, whether i can't get sender id.

**Comment by mdrichardson** [comment] 2019-12-04 19:36
@fuine6 I just tested this on a new bot and I am receiving my user ID when sending a message to the bot.

Can you provide detailed reproduction steps so that I can try to troubleshoot this?

**Comment by fuine6** [comment] 2019-12-05 02:00
I create a line group, It has two members and a bot.
![Capture2](https://user-images.githubusercontent.com/34824302/70195658-4370cb00-1741-11ea-8865-39fe964a2b0b.PNG)

First I set the webhook url to the location of ngrok.
![Capture3](https://user-images.githubusercontent.com/34824302/70196513-e1659500-1743-11ea-95a9-b51f94af10c9.PNG)

Then send a message to the group.
![Capture4](https://user-images.githubusercontent.com/34824302/70196675-7d8f9c00-1744-11ea-8bec-97cf98ea69a0.PNG)

The messages from ngrok.
```
{
    "events": [
        {
            "type": "message",
            "replyToken": "58b621b2779b4b388ca834xxxxxxxxxx",
            "source": {
                "userId": "U46eb74ae1dd9cd8772bb63xxxxxxxxxx",
                "groupId": "C7512d5c526df82ce8aa0ddxxxxxxxxxx",
                "type": "group"
            },
            "timestamp": 1575510449209,
            "message": {
                "type": "text",
                "id": "11032227677000",
                "text": "First message"
            }
        }
    ],
    "destination": "U76c146a68974eae44b20ebxxxxxxxxxx"
}
```

Then I change the webhook url.
![Capture5](https://user-images.githubusercontent.com/34824302/70196876-00b0f200-1745-11ea-93e9-30e6e8fa7e37.PNG)

Then send a message to the group.
![Capture6](https://user-images.githubusercontent.com/34824302/70196973-52597c80-1745-11ea-85c2-6afb7586a618.PNG)

The messages from ngrok.
```
{
    "type": "message",
    "id": "90f784c3f9f44e4dad52a712cd4c831f",
    "timestamp": "2019-12-05T01:53:47.4543181Z",
    "serviceUrl": "https://line.botframework.com/",
    "channelId": "line",
    "from": {
        "id": "C7512d5c526df82ce8aa0ddxxxxxxxxxx",
        "name": "LINE"
    },
    "conversation": {
        "isGroup": false,
        "id": "C7512d5c526df82ce8aa0ddxxxxxxxxxx|Iegtzf7rAtF"
    },
    "recipient": {
        "id": "Iegtzf7rAtF",
        "name": "thebot-test"
    },
    "text": "Second message"
}
```
Here is another question, should isGroup be true?

**Comment by mdrichardson** [comment] 2019-12-05 18:46
@fuine6 I believe I see where the change is needed to fix this on the backend. I will do some testing and let you know. Just FYI: it will take a couple of weeks for the change to go live after it gets fixed.

**Comment by mdrichardson** [comment] 2019-12-06 16:41
@fuine6 Just to give you an update, I spoke with the dev team about this a little.

The reason that it currently uses the group ID is because when the bot replies to the message, it needs to go to the group and not the user. The botframework schema doesn't currently allow adding an additional parameter like `from.userId`. There's currently a discussion about possible appending the userId to `from.id`, but that may break backwards-compatibility and would require additional changes elsewhere.

So, all of this is to say that we're considering adjusting this, but it may take some time. I'll update you here as I get more information.

**Comment by youyu16** [comment] 2019-12-10 06:56
@fuine6  you can get groupId/userId from activity channelData.source as a workaround

**Comment by mdrichardson** [comment] 2019-12-10 16:03
@youyu16 I thought that might be the case. Thanks for confirming.

@fuine6 I'm going to close this for now. Feel free to re-open if you don't see that it's been fixed in a couple of weeks.

**Comment by mdrichardson** [comment] 2019-12-10 16:04
Oops. Closed the wrong one.

@youyu16 Are we planning on sticking with the workaround, or will `from.userId` be changed in the future?

**Comment by youyu16** [comment] 2019-12-11 02:14
@mdrichardson still trying to find a strong solution for this one and this workaround always work if LINE don't change there webhook interface.

**Comment by mdrichardson** [comment] 2019-12-11 15:51
@youyu16 Sounds good.

@fuine6 As the workaround offers a more permanent solution, I'm going to go ahead and close this. Feel free to re-open if you disagree or have an issue relating to this.

**Closed by mdrichardson** 2019-12-11 15:51 UTC
Labels: Bot Services, customer-replied-to, customer-reported

**Comment by youyu16** [comment] 2019-12-13 02:12
Should go alive in next few weeks.
![image](https://user-images.githubusercontent.com/17819112/70763928-cbce1c00-1d90-11ea-9ac1-93d613ca6142.png)

**Comment by fuine6** [comment] 2019-12-13 06:05
> Should go alive in next few weeks.
> ![image](https://user-images.githubusercontent.com/17819112/70763928-cbce1c00-1d90-11ea-9ac1-93d613ca6142.png)

This looks good, does this mean that userId can also be obtained from from.id when the source type is group?

Currently, if the source type is group, from.id is groupId.
```
{
    "type": "message",
    "id": "a835c1b9017f4861bc28ee6eb48ac5f9",
    "timestamp": "2019-12-04T06:53:04.6195542Z",
    "serviceUrl": "https://line.botframework.com/",
    "channelId": "line",
    "from": {
        "id": "C7512d5c526df82ce8aa0ddxxxxxxxxxx", // <- group id.
        "name": "LINE"
    },
    "conversation": {
        "isGroup": false,
        "id": "C7512d5c526df82ce8aa0ddxxxxxxxxxx|Iegtzf7rAtF"
    },
    "recipient": {
        "id": "Iegtzf7rAtF",
        "name": "thebot-test"
    },
    "text": "test"
}
```

**Comment by youyu16** [comment] 2019-12-13 06:14
@fuine6 Yes, the from id will be the userId except LINE version less then 7.4.x
