### ISSUE TITLE
DirectLine: 404 Bad Argument Unknown conversation error in POST /activities API

### ISSUE THREAD

**Issue by bhushanvadgave** [microsoft/BotFramework-Services#190] opened 2020-03-05 07:56 UTC
## Overview of the issue
We have read the info in some places on the internet that the conversation ID expires (DL APIs starts giving Unknown conversation) if kept idle for a few weeks. Please confirm if this understanding is true. If it's true, I don't understand why it is not mentioned anywhere in botframework/directline documentations. 

## Impact on us
Our system is built on top of and heavily depends on the assumption that one conversation ID can be used by a user for a lifetime irrespective of if the user is inactive for a few weeks or not. And our system admin users use only the conversation IDs (not user IDs) to replay the user/bot messages even if messages are a year old.  

Also, we use Directline APIs (start conversation, post activity etc) in our server (a kind of proxy) to support conversations from unsupported channels like Whatsapp. We want to use one single conversation ID for message exchanges from a user.

## How to solve
Our system stores all the messages and user/conversation states (along with user ID, conversation ID). If botframework does not "reuse" the expired conversation ID then is there any API or a way to make the expired conversation ID active so that our system can use the same conversation ID for a user?

Requires help on this asap.

**Comment by CoHealer** [comment] 2020-03-09 21:05
Issues cited above are not the only constraints on conversation IDs. This is by design.

[https://docs.microsoft.com/en-us/azure/bot-service/bot-service-resources-identifiers-guide?view=azure-bot-service-4.0](https://docs.microsoft.com/en-us/azure/bot-service/bot-service-resources-identifiers-guide?view=azure-bot-service-4.0)

Several channels (e.g., SMS, Skype, and possibly others) have the quirk that the conversation ID assigned to a 1:1 conversation is the remote channel account ID. This quirk has two side-effects:

The conversation ID is subjective based on who is viewing it. If Participants A and B are talking, participant A sees the conversation ID to be "B" and participant B sees the conversation ID to be "A."
If the bot has multiple channel accounts within this channel (for example, if the bot has two SMS numbers), the conversation ID is not sufficient to uniquely identify the conversation within the bot's field of view.
Thus, a conversation ID does not necessarily uniquely identify a single conversation within a channel even for a single bot._

**Rules for conversation IDs**
Conversations have meaning only within their associated channel.
More than one ID may resolve to the same conversation.
Ordinal equality does not necessarily establish that two conversation IDs are the same conversation, although in most cases, it does.

**Closed by CoHealer** 2020-03-09 21:05 UTC
Labels: Bot Services, customer-replied-to, customer-reported, enhancement
