### ISSUE TITLE
Telegram - Hero card text size is limited

### ISSUE THREAD

**Issue by petrformanek** [microsoft/BotFramework-Services#257] opened 2020-10-01 15:20 UTC
Hello,
when I send a simple hero card to telegram channel I will get an error when size of the Title and Text property exceeds 200 characters.
Why there is such limitation? Telegram supports 4096 characters in a message.
Can you fix it?

Example of a hero card:
```csharp
new HeroCard
{
	Title = "title",
	Text = "long text with more than 200 characters"
};
```

**Comment by v-kydela** [comment] 2020-10-01 18:14
@petrformanek - Thank you for the question. It sounds like the Telegram connector is using the hero card text for something other than raw message text. Would it be acceptable for you to send your long text outside of the hero card?

**Comment by petrformanek** [comment] 2020-10-01 19:39
Thanks for a quick reply. Unfortunately it is not acceptable workaround as I would have to either create a channel specific reply or some customization for hero cards replies for telegram channel. The "long" text is actually not that long, it is a couple of lines which easily exceeds 200 characters.
I would rather see it fixed on telegram connector.

**Comment by v-kydela** [comment] 2020-10-02 23:59
@petrformanek - I'm afraid I cannot reproduce the issue. I send the hero card like this:

```c#
internal static async Task TestTelegramAsync(ITurnContext turnContext, CancellationToken cancellationToken)
{
    var card = new HeroCard
    {
        Title = "title",
        Text = new string('A', 201),
    };

    await turnContext.SendActivityAsync(MessageFactory.Attachment(card.ToAttachment()), cancellationToken);
}
```

And the text gets automatically truncated by the Telegram connector as expected:

![image](https://user-images.githubusercontent.com/41968495/94978001-2a0aed80-04d0-11eb-9277-7972c26c284b.png)

There may be something else wrong with your card. Please provide the following:

1. An example of a card that actually reproduces the problem
1. Repro steps
1. Screenshots
1. Links to any documentation/samples you're following

**Comment by v-kydela** [comment] 2020-10-05 20:57
@petrformanek - Are you still working on this?

**Comment by arturl** [comment] 2020-10-13 22:10
Hi @petrformanek -- we tried the scenario you described and did not see any errors. If you can tell us what error you're seeing and precise steps to reproduce it, we'll be happy to look again.

**Comment by petrformanek** [comment] 2020-10-19 11:42
Hi @v-kydela,
thanks for looking at it. Now when I have more information I can provide STR. The text needs to contain markdown. When it contains markdown and the text is cut (replaced by ...) then there is an error sending hero card to telegram.

```csharp
var card = new HeroCard
{
    Title = "title",
    Text = "*" + new string('A', 200) + "*"
};
```
In this case you will get `Microsoft.Bot.Schema.ErrorResponseException: Operation returned an invalid status code 'BadRequest'` exception. 
In case of `new string('A', 100)` you will get a bold text as expected.

**Comment by v-kydela** [comment] 2020-10-19 18:29
@petrformanek - You will not get the error if you set the text format to plain:

```c#
activity.TextFormat = TextFormatTypes.Plain;
```

@arturl - That said, it does seem like there are some problems here so I'll reopen the issue

1. Telegram card text shouldn't be limited to 200 characters
2. Markdown text should be truncated without error just like plain text

**Comment by arturl** [comment] 2020-10-19 21:02
Thanks for clarification @petrformanek we'll look into it.

**Comment by arturl** [comment] 2020-10-20 07:11
Hi @petrformanek, according to [Telegram documentation](https://core.telegram.org/bots/api#sendphoto) caption field for photo messages (which is what Hero cards are mapped to) can be up to 1024 characters long (not 4096, that's a text message limit). 
I'll change the limit to 1024.

**Comment by arturl** [comment] 2020-10-29 02:02
The fix has been deployed. Here is the output from the repro case:
![image](https://user-images.githubusercontent.com/1875734/97516317-1b3d1c80-1950-11eb-80fe-2ecadb8e6ff6.png)

**Closed by arturl** 2020-10-29 02:02 UTC
Labels: Bot Services, bug, customer-replied-to, customer-reported
