### ISSUE TITLE
directline errors

### ISSUE THREAD

**Issue by ubreddy** [Microsoft/BotFramework-Services#38] opened 2019-01-24 05:20 UTC
I keep getting directline errors once a while multiple times during the day....

e.g.
getaddrinfo ENOTFOUND directline.botframework.com directline.botframework.com:443

and
some errors like below
https://directline.botframework.com/v3/conversations/I02GjBASIPz4DOmNQeTxKL/activities/I02GjBASIPz4DOmNQeTxKL|0000000' failed: [503] Service Unavailable

https://directline.botframework.com/v3/conversations/6lg94qXdQbv6WOaUTf42YO/activities/6lg94qXdQbv6WOaUTf42YO|0000000' failed: [500] Internal Server Error

https://directline.botframework.com/v3/conversations/HBVeZlhbpVx1B1cjKD5QXS/activities/HBVeZlhbpVx1B1cjKD5QXS|0000000' failed: [502] Bad Gateway
Any reason why ? it stops our webchat conversation flow....

Appid: 3b2bea4a-c6ac-4e54-a926-cbee6a1c1d2a
One common thing for all errors is that activitiy id is always ending with |0000000

**Comment by mdrichardson** [comment] 2019-01-24 16:11
Closed. Duplicate of: https://github.com/Microsoft/BotBuilder/issues/5266

**Closed by mdrichardson** 2019-01-24 16:11 UTC
