### ISSUE TITLE
directline errors

### ISSUE THREAD

**Issue by ubreddy** [Microsoft/BotFramework-Services#39] opened 2019-01-24 09:23 UTC
I keep getting directline errors once a while multiple times during the day....

e.g.
getaddrinfo ENOTFOUND directline.botframework.com directline.botframework.com:443

and
some errors like below
https://directline.botframework.com/v3/conversations/I02GjBASIPz4DOmNQeTxKL/activities/I02GjBASIPz4DOmNQeTxKL|0000000' failed: [503] Service Unavailable

https://directline.botframework.com/v3/conversations/6lg94qXdQbv6WOaUTf42YO/activities/6lg94qXdQbv6WOaUTf42YO|0000000' failed: [500] Internal Server Error

https://directline.botframework.com/v3/conversations/HBVeZlhbpVx1B1cjKD5QXS/activities/HBVeZlhbpVx1B1cjKD5QXS|0000000' failed: [502] Bad Gateway
Any reason why ? it stops our webchat conversation flow....

Appid: 3b2bea4a-c6ac-4e54-a926-cbee6a1c1d2a

One common thing for all errors is that activitiy id is always ending with |0000000

**Comment by ubreddy** [comment] 2019-01-28 06:08
Service unavailable errors during these time periods
Timestamp: 2019-01-26T08:50:24+00:00
Timestamp: 2019-01-27T10:33:10+00:00
Timestamp: 2019-01-28T05:55:07+00:00

Internal Server error during this time
Timestamp: 2019-01-27T15:58:17+00:00

Any idea when will the directline stabilize?
These were not occurring earlier.... only in  last  2-3 weeks or so they started appearing almost on a daily basis...

**Comment by ubreddy** [comment] 2019-01-29 14:14
These are still coming almost every two hours... mostly service unavailable errors  or internal server errors...
Timestamp: 2019-01-29T14:08:19+00:00
Timestamp: 2019-01-29T13:59:15+00:00
Timestamp: 2019-01-29T13:49:46+00:00
Timestamp: 2019-01-29T12:01:27+00:00
Timestamp: 2019-01-29T11:15:44+00:00
Timestamp: 2019-01-29T09:43:45+00:00
Timestamp: 2019-01-29T09:03:52+00:00
Timestamp: 2019-01-29T08:30:20+00:00
Timestamp: 2019-01-28T06:59:13+00:00
Timestamp: 2019-01-28T05:55:06+00:00

Thought it could help in your fixing and making it stable...
Any idea when it would be get stable?

**Comment by EricDahlvang** [comment] 2019-02-13 18:55
Hi @ubreddy 

I spoke with one of the Direct Line Service engineers about the issues you've been having.  They provided this response:

> There are a couple different problems:
> 
> 1.	Errors from internal dependencies
> a.	We are in the process of moving our internal databases to CosmosDB which will give better performance and resiliency. That should be done in the next couple weeks.
> 2.	Errors from the platform
> a.	We've battling a networking problem and have engaged other Azure teams to root cause this. This is our highest priority issue.
> 3.	Errors from deployment
> a.	We are deploying some fixes that will make deployments less impactful. This should also be in place in the next couple weeks
> 
> The good news is that we're aware of each of these and making progress on their fixes. The bad news is that it's taking far too long and for that I apologize. These issues are frustrating for us, too.

**Comment by Rashree138** [comment] 2019-02-19 04:30
Hi Eric Dahlvang,

in case our issue we have already using TLS1.2 and other recommended setting. BUt still we are getting the error. so please let me what should be the changes we need to do....

Below line is raising the issue: 

<<<<<using (var response = await client.PostAsync(url, strContent).ConfigureAwait(false))>>>>>.

Thanks,
Raj

**Comment by EricDahlvang** [comment] 2019-02-19 14:35
Hi @Rashree138 

This issue is not related to TLS 1.2, but rather the service as explained here: https://github.com/Microsoft/BotFramework-Services/issues/39#issuecomment-463321808

**Comment by thedrew12** [comment] 2019-03-08 16:28
Any update on this? Today, I'm getting 502's at one point and then the API starts working.

**Comment by EricDahlvang** [comment] 2019-03-11 18:17
@thedrew12 The fix for the issue is still in progress.

**Comment by EricDahlvang** [comment] 2019-04-04 19:35
Closing this issue.  The fixes for this have been completed.

**Closed by EricDahlvang** 2019-04-04 19:35 UTC
