### ISSUE TITLE
DirectLine#There was an error sending this message to your bot: HTTP status code GatewayTimeout

### ISSUE THREAD

**Issue by rrc2k4** [microsoft/BotFramework-Services#233] opened 2020-07-09 09:50 UTC
We have noticed "There was an error sending this message to your bot: HTTP status code GatewayTimeout" error intermittently for our bot in direct line channel while it works fine in web channel.

SDK Platform: .NET
SDK Version: V3
Microsoft.Bot.Builder:3.12.2.4
Microsoft.Bot.Connector:3.12.2.4

Issue is not consistent, it happens intermittently. Had this issue on 1st July 2020 for 4-5 conversations and again on 09th July 2020(today) for 3-4 conversations. We observed this issue irregularly between 2020-07-09 07:34:45.050 and 2020-07-09 08:00:45.050 UTC time today. BOT services (End point) was fine and as is hosted in India Data Center & not in azure. There were no connectivity issues to end point as through web channel it is working fine.

09th July data(convesation id and timestamp in utc)
1) H8dDuLyjdICspPZa4v49u-5     2020-07-09 07:34:45.050
2)4TR8968C9zgErmczcgFilB-6     2020-07-09 07:46:46.920
3) m1SS1l0mUmogH3w7QtHI-6 2020-07-09 07:51:20.510

kindly let know  what could be the issue.

**Comment by arturl** [comment] 2020-07-09 16:56
Hi @rrc2k4, thanks for your report. We will look at the telemetry on our end and let you know what we see.

**Comment by arturl** [comment] 2020-07-10 05:44
@rrc2k4, I see that the first two conversations failed because the bot failed to respond in 15 seconds. Total bot time was 16132 ms and 15726 ms correspondingly. The error is reported as "Failed to send activity: bot timed out"
The third conversation (m1SS1l0mUmogH3w7QtHI-6) actually succeeded although it also took quite long (8737 ms).

So, what I see point to a problem with the bot, but me know if your want more data.

**Comment by rrc2k4** [comment] 2020-07-10 07:54
Thanks for the detailed analysis. Could you please help to analyse this conversation id as well AWsbW9vK8Wa6VqbwDxJ7Jk-j 
I missed out mentioning this id, this is the first conversation id which has started this issue, i believe it never reached the bot.

Regarding m1SS1l0mUmogH3w7QtHI-6 conversation id , bot responded(8737ms) below 15 seconds right , so it should have been a valid scenario then why did it failed?

**Comment by rrc2k4** [comment] 2020-07-10 10:10
We further did analysis of requests reached to our bot services hosted in our data center and found below details. Was only able to get  2 conversation ID's from directline so based on those details here is our analysis.
1) ConversationID:H8dDuLyjdICspPZa4v49u-5

ActivityID | DirectLine   TimeStamp | Acitivity | Message | Processed by   Bot Service | Observation
-- | -- | -- | -- | -- | --
H8dDuLyjdICspPZa4v49u-5\|0000000 | 2020-07-09T07:34:28.0502873Z | User   Query | test | 2020-07-09   07:34:45.050 | From   Directline, it took 17 seconds to reach our web server
H8dDuLyjdICspPZa4v49u-5\|0000001 | 2020-07-09T07:34:45.9419846Z | Bot   Response | I   hope to pass your tests. Feel free to test me often. | 2020-07-09   07:34:45.707 |  

2) ConversationID:m1SS1l0mUmogH3w7QtHI-6


ActivityID | DirectLine   TimeStamp | Acitivity | Message | Processed by Bot   Service | Observation
-- | -- | -- | -- | -- | --
m1SS1l0mUmogH3w7QtHI-6\|0000000 | 2020-07-09T07:51:12.8267243Z | hi | test | 2020-07-09   07:51:20.510 | From   Directline, it took 8 seconds to reach our web server
m1SS1l0mUmogH3w7QtHI-6\|0000001 | 2020-07-09T07:51:21.198047Z | Bot   Response | Greetings!   How can I assist? | 2020-07-09   07:51:20.980 |  

Note: if issue was with bot services hosted in our data center then kindly note that at same time frame we tried accessing another bot hosted on same application server & same azure subscription and there were no issues in connectivity. Reference ConversationID for that 2nd instance:Bs6TBOhmybj3vB76ylbJoO-6

**Comment by rrc2k4** [comment] 2020-07-10 10:17
I was only able to pull conversations from directline only for 2 ID's using https://directline.botframework.com/v3/directline/conversations/<<conversationid>>/activities url but for other id's it always gives  output as below, it doesn't returns conversation activities. 
{ "activities": [], "watermark": "1009"}
And from activityhistory url (https://directline.botframework.com/v3/directline/conversations/<<conversationid>>/activities/history) using GET it always throws error saying method is not allowed.

Any idea how can we pull logs from directline?

**Comment by arturl** [comment] 2020-07-10 23:19
@rrc2k4, I looked at the conversation AWsbW9vK8Wa6VqbwDxJ7Jk-j and found that it failed because of an issue in our service (failure in an in-memory database we depend on). I started an investigation and we'll be tracking this issue internally. Please accept my apologies on behalf of the product.

To get the list of activities, use the following syntax:
`/v3/directline/conversations/{conversation-id}/activities?watermark={number}`

Details on the API are available here: https://docs.microsoft.com/en-us/azure/bot-service/rest-api/bot-framework-rest-direct-line-3-0-api-reference?view=azure-bot-service-4.0#get-activities

**Comment by rrc2k4** [comment] 2020-07-13 08:52
Thanks for the details, will wait for your update on service failure.

**Comment by arturl** [comment] 2020-07-13 23:40
I'm tapping my collogue @rajivpb who let me know that the fix for the issue is already in the works and should be deployed soon. We will close this issue once the fix is out.

**Comment by rrc2k4** [comment] 2020-07-14 08:26
Sure,will wait for the fix. Thanks for the update.

**Comment by MichaelHaydenAtMicrosoft** [comment] 2020-07-24 21:59
Fix has deployed that should fix this problem. Closing issue for now.

**Closed by MichaelHaydenAtMicrosoft** 2020-07-24 21:59 UTC
Labels: customer-replied-to, customer-reported

**Comment by rrc2k4** [comment] 2020-07-27 12:58
Thanks for the update and for the fix.

May we ask some brief technical description of the issue and the fix provided, We have to inform our clients.

Thanks & Regards,
Ravi

**Comment by arturl** [comment] 2020-07-27 16:53
This was an issue with Redis component that we depend on. We upgraded the version of the Redis client that should fix it based on our analysis.
