### ISSUE TITLE
Slack buttons randomly not working and skipping logs

### ISSUE THREAD

**Issue by unemx** [microsoft/BotFramework-Services#261] opened 2020-10-15 11:01 UTC
## Context
Channel: Slack.
Installation: standard (using the link provided by bot framework)
Conversation type: 1 on 1.

## Issue
The first buttons of a conversation between the bot and a user sometime doesn't do anything. 
We can see in the logs the user initiating the conversation, having a few interactions up until the point the bot ask them to confirm something and provide a button to do so.

At this point we stop receiving logs on that interaction, for a few minutes.

Then the user's log restart after a while, but after the confirmation point (which is mandatory to pass initially).

## More details
- This seems to occur randomly. 
- The users victims to the bug, report that the button is not working properly (the bots answer that he doesn't recognize their answer).
 But does work again after a while (ranging from minutes to hours).
- We have no log for these users of either interaction (either working or not working)

### Additional information
I am happy to give you anything required to help us solve this for our clients. More specific context if needed, or the bot IDs in private DM.

**Comment by v-kydela** [comment] 2020-10-15 18:17
Thank you for the report, @unemx 

You might be interested in reading these other issues:

- https://github.com/microsoft/BotBuilder-Samples/issues/2553
- https://github.com/microsoft/botbuilder-dotnet/issues/4246

Can you determine if you're using a [classic](https://api.slack.com/rtm#classic) Slack app or not?

**Comment by arturl** [comment] 2020-10-21 16:59
@unemx, can you share the relevant portion of the bot's source code (minimal repro case would be ideal). Also if you can send me your bot id, I will look at the telemetry on our end (you can email me [here](mailto:arturl@microsoft.com))

**Comment by arturl** [comment] 2020-11-06 00:37
Closing -- cannot reproduce the problem. Feel free to reactivate if you have small self-contained repro.

**Closed by arturl** 2020-11-06 00:37 UTC
Labels: Bot Services, customer-replied-to, customer-reported
