### ISSUE TITLE
GetAadTokensAsync calls the wrong token endpoint, contrary to what was configured in Azure Portal Bot Channels Registration

### ISSUE THREAD

**Issue by dejancg** [microsoft/BotFramework-Services#256] opened 2020-09-30 11:10 UTC
## Version
Using Microsoft.Bot.Builder v4.10.3 with Microsoft Teams

## Describe the bug
`IUserTokenProvider.GetAadTokensAsync` doesn't call the token endpoint configured in Azure Portal - Bot Channels Registration - Settings. Instead, it calls what seems to be a hardcoded relative path `/connect/oauth2/token`.

## To Reproduce
1. Go to *Azure Portal -> Bot Channels Registration -> Settings*
2. Scroll down to *OAuth Connection Settings* and click *Add Setting*
3. Choose any name for *Name* input and for *Service Provider* choose **Generic Oauth 2**
4. Configure the mandatory fields as on the screenshot:
![Generic Oauth 2](https://drive.google.com/uc?export=download&id=1hAENOe7gQf0vOJ--4NWA62EPXB44jR58)
5. Also configure *Scopes* input with, for example, **openid profile roles offline_access** but it's not mandatory
6. Create a Microsoft Teams messaging extension using the bot builder which uses the following code:
```c#
var botAdapter = turnContext.Adapter as IUserTokenProvider;

// Check if the user has a token stored already in the bot framework service.
var tokenStatusList = await botAdapter
    .GetTokenStatusAsync(turnContext, turnContext.Activity.From.Id, oauthConnectionName, cancellationToken)
    .ConfigureAwait(false);

// Get the current relevant connection
var tokenStatus = tokenStatusList.FirstOrDefault(ts => ts.ConnectionName == oauthConnectionName);

// If token is found, fetch the token for the required resources
if (tokenStatus?.HasToken != null && tokenStatus.HasToken == true)
{
    // Returns 404 Not Found, because it adds "oauth2" to the path
    var tokenResponseDictionary = await botAdapter
        .GetAadTokensAsync(turnContext,
            oauthConnectionName,
            // not sure what is this for, 
            // but behaves the same even if I supply my own aud claim value from the access token
            new string[] { "https://graph.microsoft.com" }, 
            turnContext.Activity.From.Id,
            cancellationToken)
        .ConfigureAwait(false);
        
    if (tokenResponseDictionary != null)
    {
        accessToken = tokenResponseDictionary["https://graph.microsoft.com"].Token;
    }
}
```

## Expected behavior
It was expected for `GetAadTokensAsync` to send a request to the endpoint I configured, instead it sends a request to my-auth-server-url/connect/**oauth2**/token (adds what seems to be a hardcoded "oauth2" string to the token endpoint URL)

**Comment by EricDahlvang** [comment] 2020-10-01 00:21
Transferred to the BotFramework-Services

@Jeffders is this something we can address, or is this outside of our services?

**Comment by swagatmishra2007** [comment] 2020-10-01 07:30
I will take a look and report back, on what the issue is. It is something within our services, but need to see what's going on

**Comment by dejancg** [comment] 2020-10-05 08:12
Hey @swagatmishra2007, any update on this, or should we just cache our tokens locally and forget this token service exists?

**Comment by swagatmishra2007** [comment] 2020-10-06 04:45
The current code assumes that if GetAADTokens is being called, then the call is being made to login.microsoftonline.com and hence the url is constructed as such. That is why the url ends up being mangled like you see.
i am going to make some changes such that in generic oauth, this assumption is not made and hence the url remains intact, but first i am going to have to ensure that no other bot has taken a dependency on this behavior.
will update with deployment scehdule shortly (hopefully in a couple of days).
Optimistically, i am hoping to have the fix deployed early next week

**Comment by swagatmishra2007** [comment] 2020-10-14 03:43
@dejancg The fix has been deployed everywhere. Can you retry your scenario?
Feel free to re-open if the issue persists

**Closed by swagatmishra2007** 2020-10-14 03:43 UTC
Labels: Bot Services, bug, customer-replied-to, customer-reported

**Comment by dejancg** [comment] 2020-10-14 11:56
Thank you @swagatmishra2007.
It now indeed calls the correct endpoint. As a side note, it refreshes the access token successfully, but only once. It seems to assume that the refresh token is reusable and doesn't update it, but the identity provider is currently configured to issue a new refresh token each time the access token is issued. As our application is still in development phase, it shouldn't be a problem to temporarily configure the identity provider to issue a reusable token. But it might be a good idea you look into this problem as well.

**Comment by swagatmishra2007** [comment] 2020-10-14 20:06
interesting...the code seems to update the refresh token from the response it gets while asking for an access token. Let me look further into it

**Comment by SrinagaramalakshmiM** [comment] 2021-07-08 09:11
Hi ,
Regarding this getAadTokens() does the resourceurl parameter takes only resources of http urls  because when I'm trying to pass the api:// based url it was throwing an error can u pls look into this

**Comment by SrinagaramalakshmiM** [comment] 2021-07-08 09:36
@swagatmishra2007 can u pls look into this issue
