### ISSUE TITLE
DirectLine Intermittently Throwing 429 Errors

### ISSUE THREAD

**Issue by RootOfAllEval** [microsoft/BotFramework-Services#226] opened 2020-06-22 16:37 UTC
## Version
4.9.3

## Describe the bug
DirectLine API throwing 429 errors intermittently during conversation operations.

## To Reproduce
I noticed while testing our bot the last few days that DirectLine will sometimes throw 429 responses during certain blocks of time. These appear to be unrelated to the volume of bot messages being sent as they go away during other times. 

## Screenshots
![image](https://user-images.githubusercontent.com/5480993/85312527-f4904600-b484-11ea-91c1-b2f2e2577d9d.png)

**Comment by dandriscoll** [comment] 2020-06-22 18:19
Hello, there are two possible causes for this issue:

1. Your client is sending traffic that has triggered our rate limiting logic. We have had bugs in prior versions of Web Chat and DirectLine-JS that can contribute to this problem. Please make sure any copies of Web Chat and DLJS are the latest version.
2. We occasionally encounter service instability that causes these 429s. We did experience these between 2-4 hours ago, and have resolved the problem. If you see further 429s not caused by outdated Web Chat / DLJS, please open a new ticket.

**Comment by dandriscoll** [comment] 2020-06-22 18:20
If you happen to see 429s that persist beyond a few hours, even on the latest Web Chat, please send a conversation ID where you experienced the problem and we will investigate. (Conversation IDs are completely random and assigned by Direct Line.)

**Comment by RootOfAllEval** [comment] 2020-06-22 18:57
Thanks for the response @dandriscoll! The pattern of instability you mentioned does seem to fit the cases I've seen on my end, so it seems like it's most likely a service issue. Are there any steps we can take on our end to mitigate such issues? Our bot has high visibility with our customers, so we get a lot of reports during degradations/downtime. Also, it doesn't seem like the [Azure Status page](https://status.azure.com/en-us/status) ever displays any indications of service degrations when we've experienced these issues.

**Comment by dandriscoll** [comment] 2020-06-22 20:08
The most important thing you can do is to make sure your version of Web Chat and DLJS are updated. This is the primary contributor to 429 errors.

We update the Azure Status page when an issue persists, but typically we are able to resolve the issue before those updates are posted and visible.

I'll close this issue now as the service problem has been mitigated. (In the event that it resurfaces, we have improved monitoring on its way to production now that will give us more notice when this occurs.) If you encounter problems, please post an update or file a new ticket.

**Closed by dandriscoll** 2020-06-22 20:08 UTC
Labels: Bot Services, customer-reported
