### ISSUE TITLE
Reconnect to a conversation in Direct Line API 3.0

### ISSUE THREAD

**Issue by mmiele** [microsoft/BotFramework-Services#319] opened 2021-09-15 17:55 UTC
Following the user’s intent as described in the issue: [Generate a new WebSocket stream URL #2050](https://github.com/MicrosoftDocs/bot-docs/issues/2050), it sounds like the reconnect endpoint is returning the full conversation history regardless of if the ‘Watermark’ parameter is sent or not. 
Reading the article [Reconnect to a conversation in Direct Line API 3.0](https://docs.microsoft.com/en-us/azure/bot-service/rest-api/bot-framework-rest-direct-line-3-0-reconnect-to-conversation?view=azure-bot-service-4.0), assuming that it’s correct,  it seems that this is a bug. From the documentation point of view, we need to know if the current behavior is by design and some explanation for the customer. Please advice.

**Comment by JonathanFingold** [comment] 2021-09-15 18:10
@MichaelHaydenAtMicrosoft 
- Michael Miele asked Daniel Evans, who thought that the watermark was not working correctly, but Daniel was not 100% sure.

**Comment by craigjensen** [comment] 2021-09-15 18:22
@mmiele Please attach a conversationId and approx timestamp and I'll see if I can figure out where the issues is.

**Comment by mmiele** [comment] 2021-09-20 18:24
> @mmiele Please attach a conversationId and approx timestamp and I'll see if I can figure out where the issue is.

This is the doc issue opened by the customer: https://github.com/MicrosoftDocs/bot-docs/issues/2050

**Comment by JonathanFingold** [comment] 2021-09-20 18:44
@craigjensen please follow up with https://github.com/Mohammed-Ahmed-Ismail for more information.

**Comment by craigjensen** [comment] 2021-09-20 19:16
@Mohammed-Ahmed-Ismail Please attach a conversationId and approx timestamp and I'll see if I can figure out where the issue is.

**Comment by MichaelHaydenAtMicrosoft** [comment] 2021-09-27 18:50
@Mohammed-Ahmed-Ismail, are you able to attach a conversationid and timestamp? We will need to this in order to troubleshoot further.

**Comment by MichaelHaydenAtMicrosoft** [comment] 2021-10-04 18:51
Closing for now. We tested on our end and bot is responding. Please re-open if issue reoccurs

**Closed by MichaelHaydenAtMicrosoft** 2021-10-04 18:51 UTC
Labels: customer-replied-to, Waiting on Customer Response
