### ISSUE TITLE
MS Teams channel is giving exception when Comsmos DB is used for state managment in Enterprise Bot Template V4.

### ISSUE THREAD

**Issue by sw-ms-roshanparmar** [Microsoft/BotFramework-Services#27] opened 2018-11-28 05:03 UTC
**Description**

Currently I am using Enterprise Bot Template v4 SDK C# for developing the bot. I am using Cosmos DB for user state management. Everything works fine with enterprise bot template , but when configure the bot on MS Teams channel , at that point of time Bot fails to write the state data to Cosmos DB and gives an error

**What is actually happening..**
Cosmos DB(document DB) handles every individual row/data uniquely by "id" column. Cosmos DB is having a limitation of the length of the "Id" which is 255 characters.
Now, when bot tries to store the user state for MS Teams channel in cosmos db , at that point of time Enterprise bot template/ bot framework v4 automatically creates an unique id which has length more than 255 characters. So this gives an exception in code.

Please someone look into this issue as this is a blocking issue for ms teams.

As a workaround of this issue i managed to store the state in blob storage and deployed my bot.

**Exception call stack**

Description

Currently I am using Enterprise Bot Template v4 SDK C# for developing the bot. I am using Cosmos DB for user state management. Everything works fine with enterprise bot template , but when configure the bot on MS Teams channel , at that point of time Bot fails to write the state data to Cosmos DB and gives an error

What is actually happening..
Cosmos DB(document DB) handles every individual row/data uniquely by "id" column. Cosmos DB is having a limitation of the length of the "Id" which is 255 characters.
Now, when bot tries to store the user state for MS Teams channel in cosmos db , at that point of time Enterprise bot template/ bot framework v4 automatically creates an unique id which has length more than 255 characters. So this gives an exception in code.

Please someone look into this issue as this is a blocking issue for ms teams.

As a workaround of this issue i managed to store the state in blob storage and deployed my bot.

**Error Call Stack**

Message: {"Errors":["The input name 'msteams*2fconversations*2fa:1de_GDChOYejATRlAuinJGMmbe2YZQ3SdEB7EPvQ_WOIUSTuU64GB5HP9BX8ol2oo1WPck-s-RpJWbMo3X9fayx-OFmyF3LnBgs7jDYj79WniZvCMqbZZy8M5RPLh2MXm*2fusers*2f29:1RNNKZBhoBQm0hQVbvY5NwyFWEsXABeNQUxZEHPwUYkjfn_whINgbuk6cnw21K1zFSF_ozHXBkBRJfXTLfMgbXA' is invalid. Ensure to provide a unique non-empty string less than '255' characters."]}
ActivityId: ad22f7b1-1572-406f-9440-b77f328239a0, Request URI: /apps/c8f5225c-4725-4992-9a92-6dd3f3d1510b/services/82820cba-3446-437f-8667-0a3eac3be57f/partitions/db603d54-4640-4e74-a0bc-aa19ce2198a3/replicas/131862185541974409p/, RequestStats: 
RequestStartTime: 2018-11-29T12:08:33.5809299Z, Number of regions attempted: 1
, SDK: Microsoft.Azure.Documents.Common/2.1.0.0, Windows/10.0.17134 documentdb-netcore-sdk/1.9.1

**Comment by dmvtech** [comment] 2018-11-29 16:50
Investigating

**Comment by dmvtech** [comment] 2018-11-29 23:40
Closing as duplicate of #https://github.com/Microsoft/botbuilder-dotnet/issues/1197

**Closed by dmvtech** 2018-11-29 23:40 UTC
