### ISSUE TITLE
Welcome message is duplicated in Facebook channel

### ISSUE THREAD

**Issue by turbozapekanka** [microsoft/BotFramework-Services#165] opened 2020-01-07 17:59 UTC
I'm using the following pattern used in multiple samples and it works fine in WebChat and Emulator channels but when I connected my bot to the Facebook channel it sends a duplicate welcome message.

        protected override async Task OnMembersAddedAsync(IList<ChannelAccount> membersAdded, ITurnContext<IConversationUpdateActivity> turnContext, CancellationToken cancellationToken)
        {
            var welcomeText = "Hello and welcome!";
            foreach (var member in membersAdded)
            {
                if (member.Id != turnContext.Activity.Recipient.Id)
                {
                    await turnContext.SendActivityAsync(MessageFactory.Text(welcomeText, welcomeText), cancellationToken);
                }
            }
        }

Is this a sample issue or something is wrong with the Facebook channel?

![Duplicate welcome facebook](https://user-images.githubusercontent.com/20775323/71917195-20bd4200-3145-11ea-9ed7-74f47c2d6f22.PNG)

**Comment by turbozapekanka** [comment] 2020-01-08 16:40
It looks like Bot's member.Id for Facebook channel is wrong, it has both user's and bot's ids combined with "-":

![image](https://user-images.githubusercontent.com/20775323/71997291-3d1fb400-3203-11ea-8ecd-f3e4f13ea206.png)

Is this intentional or should be considered a bug?

**Comment by anusharavindrar** [comment] 2020-01-08 22:21
@turbozapekanka just to give more context on the same. 

>The way that the bot stores user information (userState) and the way Facebook does is very different. UserState is created and maintained by the bot developer (you). Facebook ALSO maintains a list of people that have connected to an app, either through the facebook apps such as games, or via Messenger. Facebook stores this information in either PSIDs or ASIDs, accessable through the Facebook Graph API v2.0

>On the bot framework side, the turnContext.Activity.MembersAdded is hit when a facebook user first connects with the bot (and thus creates their PSID or ASID to be stored in the Facebook Graph API). You could, theoretically, go in and clear the PSIDs/ASIDs from your Facebook app (the bot) on the Facebook side, but bear in mind that once a ASID/PSID is created for a Facebook user, that's THEIR ASID/PSID. If they're removed from the bot so they could be "reconnected", Facebook Graph is going to give them back that same PSID/ASID and thus the .MembersAdded flag is not going to trip and you'll be left right where you were. 


Having said that, I am having difficulty to repro the issue as I am getting the 'Hello and Welcome' message just once. Can you share the steps to repro so that I can give it a try on my end?

**Comment by turbozapekanka** [comment] 2020-01-09 16:05
The repro steps are below:
1. Deploy Echo bot https://github.com/microsoft/BotBuilder-Samples/tree/master/samples/csharp_dotnetcore/02.echo-bot to Azure.
2. Connect bot to Facebook messenger using instructions https://docs.microsoft.com/en-us/azure/bot-service/bot-service-channel-connect-facebook?view=azure-bot-service-4.0#connect-a-bot-to-facebook-messenger
3. Message to the facebook page using facebook messenger

**Comment by anusharavindrar** [comment] 2020-01-09 20:32
@turbozapekanka do you get the 'Hello and Welcome' message twice every time you connect your echo bot to the facebook channel(connected to the same user or the same page/app) or every time you test, do you create a new page and connect it to the bot(and still get the welcome message twice)?

**Comment by turbozapekanka** [comment] 2020-01-09 21:09
I only get it the first time I send a message. To reproduce this I used another facebook account, added it to testers role in facebook app, and messaged from a new account. Subsequent messages do not trigger OnMembersAddedAsync method at all, so I do not receive _any_ welcome message. I don't know how to make the bot forget about previous conversation and start over.

**Comment by anusharavindrar** [comment] 2020-01-13 18:22
@turbozapekanka  its how Facebook handles the user information on their end. Facebook maintains a list of people that have connected to an app, either through the facebook apps such as games, or via Messenger and stores this information in either PSIDs or ASIDs, accessable through the Facebook Graph API v2.0.

As per this behavior, when you connect a **new facebook account(user)** to the bot **for the first time**, the 'OnMembersAddedAsync' is triggered and the welcome message is displayed. The next time when you connect the bot to the facebook channel on the same user, you will not be getting a welcome message as the 'OnMembersAddedAsync' is not triggered. Even if you go ahead and clear the PSIDs/ASIDs from your Facebook app (the bot) on the Facebook side, the next time you try to reconnect, Facebook Graph is going to give them back that **same PSID/ASID** and thus the .MembersAdded flag is not going to get triggered. **Only when you connect to a new account for the first time, the OnMembersAddedAsync will be triggered**. Hence, **you cannot make the bot forget the previous conversation and start over on the facebook channel.**

Note: I am going to test extensively using a new account and try to repro what you are encountering and update the thread.

**Comment by anusharavindrar** [comment] 2020-01-17 17:45
@turbozapekanka I am currently in the process of reproducing your issue. Have you encountered the same issue on the FB channel using some other sample as well other than the echo-bot sample?

**Comment by turbozapekanka** [comment] 2020-01-17 19:59
I haven't checked other examples but I believe any example that uses this condition "if (member.Id != turnContext.Activity.Recipient.Id)" will behave the same.

**Comment by anusharavindrar** [comment] 2020-01-24 17:46
@turbozapekanka for some weird reason I am not able to repro the behavior which you are experiencing. Having said that, can you test one instance on your end by adding a new facebook account but not adding it to the testers role in the app and see if you can still repro the issue(getting duplicate welcome message)?

**Comment by turbozapekanka** [comment] 2020-01-27 20:21
If I don't add the user to testers it will not work at all because facebook app will not be available, it requires business or individual verification in order to work with regular users.

**Comment by anusharavindrar** [comment] 2020-02-11 18:27
@turbozapekanka apologize for the delay in response. I will update the thread shortly. I am trying to test using the business/brand page option.

**Comment by anusharavindrar** [comment] 2020-02-20 23:27
@turbozapekanka I am able to repro the issue on my end when I connect a new account/app to my bot. I am suspecting it to be related to how it is handled on the Facebook end(ID generation) since as per the bot code, it should just trigger once. I will update the thread once I am able to get more info on how this is being handled on Facebook's end.
![turFB](https://user-images.githubusercontent.com/48731427/74989477-494b8380-53f5-11ea-8dd4-3e362460ce27.png)

**Comment by turbozapekanka** [comment] 2020-02-21 16:52
@anusharavindrar Great to hear that you could repro. The cause is most likely due to member's ID is incorrect as shown on my screenshot above.

**Comment by anusharavindrar** [comment] 2020-02-27 21:53
@turbozapekanka thank you for your patience. You were right, the issue was due to the fact that the channel is sending the wrong recipient id in the conversation update activity. A PR for this fix is already underway and would be merged in next week's build. You could hopefully be able to test it later next week to get the correct behavior.

Hope this helps.

**Comment by anusharavindrar** [comment] 2020-03-03 19:24
Closing the issue as the fix should be out in this week's merge. Please feel free to reopen this if the issue persists.

**Closed by anusharavindrar** 2020-03-03 19:24 UTC
Labels: Bot Services, customer-replied-to, customer-reported
