### ISSUE TITLE
Users are intermittently receiving onTurnError: " Conversation not found"

### ISSUE THREAD

**Issue by craigcliff** [microsoft/BotFramework-Services#220] opened 2020-06-02 08:10 UTC
SeeNode version: v10.14.1
OS: Microsoft Windows [Version 10.0.14393]
BotBuilder NodeJS SDK v4.8.0
Channel: MSTeams

Good day,

Our Teams users are intermittently experiencing an unhandled error: Conversation not found, when conversing with the Bot, in Production.

Below are examples of 2 users that experienced this problem.

{ timeStamp: 2020-06-02T07:25:32.740Z,
  user: '*********',
  text: 'cancelled',
  channelId: 'msteams',
  activityID: 'f:4075660803462768582',
  converstationID:
   'a:1S7ngmWViRyVMbSJsQ6XeYtpL4_JnWP1XUn9m-krFbRwIN95XPiaVAG1CglU42fudfuHa5HxJFwC689Co1fmmm7r1RcOlhXFmQGyrKmDf7Po2gvUTJKm1tc61BEn0DRp9' }
Running dialog with Message Activity, awaiting user Input

 [onTurnError] unhandled error: Error: Conversation not found.

{ timeStamp: 2020-06-02T14:08:49.640Z,
  user: '*************',
  text: 'submit',
  channelId: 'msteams',
  activityID: 'f:8576363965336088120',
  converstationID:
   'a:106e7kZyRYk8zPNWOXF_1GaRKCQhpkXT3LIVCiLxljAjQvp3wL6GZayiACHDFl1cVibxlURqZ-hLimWg59ked6YeYXp5nwHDfDQHiXUXtiwnkWKuohUk0z3jPSsjkAbIx' }
Running dialog with Message Activity, awaiting user Input

 [onTurnError] unhandled error: Error: Conversation not found.

I'm unable to reproduce this error when testing in our DEV environment.

Please can I be given some guidance as to how to get around this?

**Comment by dmvtech** [comment] 2020-06-02 18:15
@Wajeed-msft Any thoughts on this one?

**Comment by Gousia-MSFT** [comment] 2020-06-03 08:12
@craigcliff Could you please share the Bot id?

**Comment by craigcliff** [comment] 2020-06-03 08:48
@Gousia-MSFT 

Hi, the ID is as follows:  203d0b8b-a4a0-43ee-b64e-5100f81d297a

**Comment by Gousia-MSFT** [comment] 2020-06-09 06:54
@craigcliff We are checking this internally.

**Comment by craigcliff** [comment] 2020-06-10 06:28
> @craigcliff We are checking this internally.

Thanks @Gousia-MSFT

**Comment by Gousia-MSFT** [comment] 2020-06-16 13:49
@craigcliff Could you please share the timestamp of when the issue happened?

**Comment by craigcliff** [comment] 2020-06-16 18:17
@Gousia-MSFT 
I don't have record of the previous failures timestamps, I have however since then enabled app insights on the webapp.

The most recent failure details are as follows:

```
Event time | 6/15/2020, 7:18:29 PM (Local time)

Error: Conversation not found., timestamp: Mon Jun 15 2020 17:18:25 GMT+0000 (Greenwich Mean Time), user: ********* *********,  text: 
****************************************************
, channelId: msteams, activityID: 1592241505802, converstationID: a:1bo1nUp9XHwdtSCvV4QU-_5sbBYY2h9M_IwTMdzNYV54gN0nEjS7JeiOpTcC7e5AD2nk4zBZy6lLQpZsVY_uPMAU0NPLtgmvz5qOKqn33QQH6HyHcKrKXmBTgDXpoxyDL  

```

The event before the "conversation not found" error above, reflects the following:


> Event time | 6/15/2020, 7:18:28 PM (Local time) |  
> 
> Dependency type | HTTP |  
> Result code | 404 |  
> Dependency call status | false |  
> Dependency duration | 1.5 s |  
> Remote dependency name | PUT /emea/v3/conversations/a%3A1bo1nUp9XHwdtSCvV4QU-_5sbBYY2h9M_IwTMdzNYV54gN0nEjS7JeiOpTcC7e5AD2nk4zBZy6lLQpZsVY_uPMAU0NPLtgmvz5qOKqn33QQH6HyHcKrKXmBTgDXpoxyDL/activities/1592223393534

**Comment by Gousia-MSFT** [comment] 2020-06-23 07:19
@craigcliff We were able to identify the root cause of the issue. We have raised a bug to track this.

**Comment by craigcliff** [comment] 2020-06-24 09:45
@Gousia-MSFT 
Thanks, the bug appears to be happening more frequently.  Yesterday in particular the error occurred 4 times:

> Error: Conversation not found., timestamp: Tue Jun 23 2020 10:58:47 GMT+0000 (Greenwich Mean Time), channelId: msteams, activityID: f:1954948730978387901, converstationID: a:1wdYXeZf9DbSHMRn40POzB3eYG2qahLHNDrzo_UDOTVXAXH0YtAe5D90RPDOo45Xc5tlaRg08CPabHwUD45bbbUt7KwODRHxFQdOy5ew0u-8wIsnYFgbYHSiuylLoYM-y  

> Error: Conversation not found., timestamp: Tue Jun 23 2020 13:50:59 GMT+0000 (Greenwich Mean Time), channelId: msteams, activityID: f:4911821228661420490, converstationID: a:1BQ9Gxz51tiVOA6wFqOTGzLbZnBgfsEOYnLVKr9EESNVWdsZc4YXLDTsBuqMIekeI_qpVrEvv6RmJOLsUF8kdMm3Ivza7CyOGzARt8wtq4P0nICwHLcW4Kda-tgHfwei7  

> Error: Conversation not found., timestamp: Tue Jun 23 2020 11:53:15 GMT+0000 (Greenwich Mean Time), channelId: msteams, activityID: f:8259692861461285434, converstationID: a:1Nwv5Oj3nXmAGf37bSLKn6rtJzEMMG1_DKbopHbtKnrHBlqBKJcolw40cCL5QE3Q5sO6zxgYV2kYLtnBospJNf9mm9sY6FBEcHwwLmJewQ4DD31VtXafuAgp0OhI7oK4Y  


> Error: Conversation not found., timestamp: Tue Jun 23 2020 13:08:10 GMT+0000 (Greenwich Mean Time), channelId: msteams, activityID: f:5450212550131137220, converstationID: a:1pLGGj8l8SBoNK9lDz34DZbOKKLlWwhWh7ddkaZufcfqWMCrFD9lPxSivDswgesi2elJlHp9u7cVP97xSw-QVSADPMLezG9YOwyQHe_Vv5_kcDE1LviY2Pcl5gYRm0i33

**Comment by Gousia-MSFT** [comment] 2020-06-26 08:02
@craigcliff Thanks for sharing this information. We are actively working on the bug fix.

**Comment by Wajeed-msft** [comment] 2020-08-04 06:29
Internal Tracker: [Bug 2187287: SMBA maps all 404 responses to return "Conversation not found" error message](https://skype.visualstudio.com/SCC/_workitems/edit/2187287)

**Comment by craigcliff** [comment] 2020-08-10 19:07
> Internal Tracker: [Bug 2187287: SMBA maps all 404 responses to return "Conversation not found" error message](https://skype.visualstudio.com/SCC/_workitems/edit/2187287)

Hi, 

I'm unable to access the link above - i get an access denied page.

Is there any progress on this issue?  It appears to be happening more frequently of late.

**Comment by tacri** [comment] 2020-08-10 20:38
@craigcliff , are you still seeing this issue? There was a bug related to PUT requests which was fixed and deployed WW. At this point the "Conversation not found" should be returned **consistently** for a given thread/activity if the channel or message was deleted and the bot is trying to update it.

**Comment by clearab** [comment] 2020-08-17 21:31
Hi! I'm going to go ahead and close this issue, please let me know if the issue persists.

**Closed by clearab** 2020-08-17 21:31 UTC
Labels: MSTeams-Developer-Support
