### ISSUE TITLE
Typing indicator not working in slack

### ISSUE THREAD

**Issue by scipe** [microsoft/BotFramework-Services#259] opened 2020-10-06 13:59 UTC
Typing indicator not working in slack, but works in MS Teams. 

## Version (NodeJS)
    "botbuilder-adapter-slack": "^1.0.13",
    "botbuilder-storage-mongodb": "^0.9.5",
    "botkit": "^4.10.0",

## Describe the bug
I trying to send "typing" indicator to MS Teams and Slack. It working great in MS Teams, but not working at all in Slack.

## To Reproduce
```await this.bot.reply(this.message, { type: 'typing' })```

## Expected behavior
User should see "typing" indicator in Slack and in MS Teams. But can see that only in MS Teams

## Screenshots
There is no screenshot for that :)

**Comment by lzc850612** [comment] 2020-10-08 18:31
Transferring to BotFramework-Services repo

**Comment by hristp** [comment] 2020-10-09 20:45
This is a bug. Slack channel implements SendTypingActivityToUserAsync -- need to figure out why it's not showing up.

Documentation [here](https://docs.microsoft.com/en-us/azure/bot-service/bot-service-channels-reference?view=azure-bot-service-4.0#uncategorized) is incorrect. Typing is supported by multiple channels (DirectLine, Facebook, Slack, Kik and Telegram, I think). Docs needs update.

**Comment by craigjensen** [comment] 2020-10-19 19:03
Slack [typing indicators](https://api.slack.com/events/user_typing) are only supported on the old RTM api which is no longer supported by the botframework so this is by design

**Comment by arturl** [comment] 2020-10-19 21:01
Thanks @craigjensen. @scipe, we'll look into adding typing support if there is a new API we can use but for now this is by design.

**Closed by arturl** 2020-10-19 21:01 UTC
