### ISSUE TITLE
Operation returned an invalid status code 'Gone'

### ISSUE THREAD

**Issue by ashok-dot** [microsoft/BotFramework-Services#268] opened 2020-11-25 11:37 UTC
Hi,

I am facing one issue chatbot application after migrated the luis app. Bot Info
Bot Framework SDK Version: 4.3.2
SDK Platform: .NET Core 3.1
Active Channels: Microsoft Teams Chatbot
Deployment Environment: Azure App Service (West Europe)

I am facing the below issue after migrated LUIS ,it changed appkey,appID and hostname , i have configured correctly and save. i was restart machine ,i am check local emulator not working,then i was deployed to azure server checked chatbot still showing some error message " Operation returned an invalid status code 'Gone'".

var luisApplication = new LuisApplication(
Environment.GetEnvironmentVariable("LuisAppId"),
Environment.GetEnvironmentVariable("LuisAPIKey"),
Environment.GetEnvironmentVariable("LuisAPIHostName")
); 

Can you please help me on this issue. Thank you .

**Comment by jwiley84** [comment] 2020-11-25 18:28
Closing as a duplicate of: https://stackoverflow.com/questions/65004353/operation-returned-an-invalid-status-code-gone

**Closed** 2020-11-25 18:29 UTC
