### ISSUE TITLE
Integration of Livezilla(version 8.0.1.6) (a third-party application with Microsoft Bot Framework)

### ISSUE THREAD

**Issue by Amita-PM** [microsoft/BotFramework-Services#159] opened 2019-12-23 09:10 UTC
There are APIs to create session and send message from Azure Bot Framework to Livezilla. But we don't have an API to retrieve any message from Livezilla into Bot Framework. 
The documentation provided by Livezilla directs user to communicate through webhooks. Currently we are able to retrieve a response from Livezilla which doesn't have the user-agent conversation, which is needed to showcase on the bot for this functionality. 
Can anyone help us out ?

Thanks

**Comment by mdrichardson** [comment] 2019-12-23 16:09
Closing here as this is a [duplicate of a StackOverflow post](https://stackoverflow.com/questions/59452963/livezilla-version-8-0-1-6-integration-with-microsoft-bot-framework-sdk-v4), which is the more appropriate forum for this request.

**Closed by mdrichardson** 2019-12-23 16:09 UTC
