### ISSUE TITLE
Unable to validate JWT tokens. OpenID provider spec is not correctly implemented

### ISSUE THREAD

**Issue by mmiele** [microsoft/BotFramework-Services#302] opened 2021-05-26 23:18 UTC
This issue cannot be addressed in documentation, see https://github.com/MicrosoftDocs/bot-docs/issues/2064 opened by https://github.com/nvioli. 

According to the [OpenID provider spec](https://openid.net/specs/openid-connect-discovery-1_0.html#ProviderConfig),
> OpenID Providers supporting Discovery MUST make a JSON document available at the path formed by concatenating the string /.well-known/openid-configuration to the Issuer.

and in section 4.3,

> The issuer value returned MUST be identical to the Issuer URL that was directly used to retrieve the configuration information. This MUST also be identical to the iss Claim value in ID Tokens issued from this Issuer. 

The `iss` field of the JWT token provided by the Bot Connector is `https://api.botframework.com`, but the metadata / configuration document is located at `https://login.botframework.com/v1/.well-known/openidconfiguration` (and alternatively, `https://api.botframework.com/v1/.well-known/openidconfiguration`). Note the extra `v1/` in the path.

Microsoft is not correctly implementing the OpenID provider spec, which makes JWT validation impossible using some popular services and libraries which expect strict adherence. In my case I wish to validate the JWT token with AWS API Gateway, but I am unable to do so.

Editing to add the error received to help others searching for this issue: `invalid_token: the issuer in the OIDC discovery endpoint metadata does not match the configured issuer`.

**Comment by willportnoy** [comment] 2021-05-28 00:21
Can you use a custom authorizer with AWS API Gateway that lets you specify the OIDC document location?

It seems like it might be a common situation - for example, the issuer field on https://login.microsoftonline.com/contoso.com/.well-known/openid-configuration is https://sts.windows.net/6babcaad-604b-40ac-a9d7-9fd97c0b779f/.

**Comment by willportnoy** [comment] 2021-06-03 17:38
@nvioli I had hoped that there was a workaround where you could specify the OIDC location as simple configuration (since it seems like a common need).

(I agree with your reading of the specification)

Although we might be able to add additional routes to serve the OIDC at the proper path, we won't easily be able to fix the issue in our other clouds (the "domain" of the issuer doesn't match the domain where we host the OIDC).

**Comment by MichaelHaydenAtMicrosoft** [comment] 2021-06-11 17:42
Issue is mitigated for public cloud. Closing for now. Please reopen if this breaks again.

**Comment by nvioli** [comment] 2021-06-11 17:56
@MichaelHaydenAtMicrosoft I'm not sure what that comment means. If you're using the presence of a workaround in my specific use case to argue that the issue is mitigated, I disagree. The issue is about noncompliance with a spec, and the whole point of having standards is that developers should not need to build workarounds.

@willportnoy, you mentioned that it may be possible to add routes to serve the OIDC at the proper path. Is there an issue to track that work? This issue is about the botframework's JWT implementation, so mention of other Microsoft clouds is irrelevant.

**Comment by willportnoy** [comment] 2021-06-15 16:20
@nvioli Bot Framework also has a presence in the other Microsoft clouds, and adding additional routes in those clouds won't mitigate the issue (because the JWT issuer doesn't match the OIDC url host name).

I'm looking into adding the additional route in the public cloud to mitigate this issue.

**Comment by willportnoy** [comment] 2021-06-24 18:40
@nvioli I've added the other route to help mitigate your issue.

https://api.botframework.com/.well-known/openid-configuration

**Closed by willportnoy** 2021-06-24 18:40 UTC
