### ISSUE TITLE
SuggestedActions behaving differently on Facebook Messenger 

### ISSUE THREAD

**Issue by neiltaylormade** [microsoft/BotFramework-Services#31] opened 2018-12-06 11:07 UTC
## Version
v4.1.5

## Describe the bug
When using SuggestedActions as below, there is differing behaviour between the emulator/web chat and facebook messenger. 

```
var opts = new PromptOptions
{
    Prompt = new Activity
    {
        Type = ActivityTypes.Message,
        Text = "Choose from one of the following options",
        TextFormat = TextFormatTypes.Plain,
        SuggestedActions = new SuggestedActions
        {
            Actions = new List<CardAction>
            {
                new CardAction
                {
                    Type = ActionTypes.PostBack,
                    Title = "Really really long button title",
                    Value = "Value1"
                },
                new CardAction
                {
                    Type = ActionTypes.PostBack,
                    Title = "Extra extra long button title",
                    Value = "Value2"
                }
            }
        }
    }
};

return await stepContext.PromptAsync(ButtonOptionPrompt, opts, cancellationToken);
```

I've written a small test app which replies back to the user with the value of the suggested action selected. When using the emulator or the test web client, the value is returned correctly. When using Facebook Messenger, the Title is returned as in the screenshots below. Added to this, only the title with the ellipsis is returned. 

```
private static async Task<bool> ValidateButtonAsync(PromptValidatorContext<string> promptContext, CancellationToken cancellationToken)
{
    await promptContext.Context.SendActivityAsync($"The value of the button you selected is: {promptContext.Recognized.Value}", cancellationToken: cancellationToken);

    return true;
}
```

## Expected behaviour
Facebook messenger should return the Value of the card action back to the bot framework.

## Screenshots
Web Chat
![screenshot 2018-12-06 at 11 01 15](https://user-images.githubusercontent.com/17292266/49580323-97867b00-f946-11e8-9f13-fb92d75e705b.png)

Facebook Messenger
![screenshot 2018-12-06 at 10 59 39](https://user-images.githubusercontent.com/17292266/49580333-9a816b80-f946-11e8-857d-e79f65e0a2b8.png)

cc @darrenj @suneetnangia

[bug]

**Comment by CoHealer** [comment] 2020-01-31 21:05
This is still a Facebook channel specific issue. Closing as by design.

**Closed by CoHealer** 2020-01-31 21:05 UTC
Labels: enhancement, facebook
