### ISSUE TITLE
smba.trafficmanager.net/amer returning 404  when sending Teams message

### ISSUE THREAD

**Issue by martinlarosa** [microsoft/BotFramework-Services#349] opened 2022-11-07 15:39 UTC
I'm receiving a lot of errors from the bot backend when trying to reply to a user in Teams. This is not happening to my particular user so I can't reproduce it.

The exception I'm seeing being logged is a Not Found being returned by:
POST `https://smba.trafficmanager.net/amer/v3/conversations/{id}/activities/{id}`

I'm using a C# bot with Bot Framework Composer  and using 4.17.2 version of the Bot Builder SDK
Anything you know or that I should consider for troubleshooting this?

**Comment by boydc2014** [comment] 2022-11-11 02:02
Hi, @martinlarosa this url is the Teams service url where bot sending messages to, is this a transient issue or a persistent issue? 

If you have a few particular timestamps of failed requests, i can route this to Teams service team for further investigation.

**Comment by martinlarosa** [comment] 2022-11-11 15:35
It used to happen sparsely, but now it's happening a lot. Multiple times an hour when I created the ticket, less so now.

2022-11-11 01:56:22.352 UTC
2022-11-11 01:56:34.082 UTC
2022-11-11 02:19:13.028 UTC
2022-11-11 02:34:40.545 UTC

**Comment by martinlarosa** [comment] 2022-12-05 19:36
Hi! I wanted to know if there's any news on this?

**Comment by boydc2014** [comment] 2022-12-06 03:54
Sorry for the delay, @martinlarosa, I've opened a ticket to Teams messaging API team. Will let you know once they get feedback

**Comment by martinlarosa** [comment] 2022-12-12 14:59
Hi @boydc2014, thank you for opening that ticket. Is that publicly available or something internal?
It's happening a lot and caused us a production issue with a customer last week.

**Comment by aosolis** [comment] 2022-12-16 22:11
The response to the 404 should contain a code that indicates what could not be found. See https://learn.microsoft.com/en-us/microsoftteams/platform/bots/how-to/conversations/conversation-messages?tabs=dotnet#status-codes-from-bot-conversational-apis

<img width="444" alt="image" src="https://user-images.githubusercontent.com/767208/208197331-4c371731-bf75-4826-ba4a-935cab34a0d6.png">

For this POST /v3/conversations/{id}/activities endpoint, the usual reason is the referenced conversation ID has been deleted.

**Comment by martinlarosa** [comment] 2022-12-21 17:34
I don't see this in the logs, the message is being sent through Bot Framework .net sdk.

**Comment by luhan2017** [comment] 2022-12-22 09:19
@martinlarosa, It's an internal ticket, they are asking for more information
Can you please share more details like tenant id, request id?
Here is the link:
https://portal.microsofticm.com/imp/v3/incidents/details/353458654/home

**Comment by aosolis** [comment] 2022-12-22 21:53
The error code is in the body of the response, which is captured in the Exception or Error object thrown by the SDK. The content will be similar to the one below:
```json
{"error":{"code":"ConversationNotFound","message":"Conversation not found."}}
```
See for example the `Body` property of `ErrorResponseException`: https://github.com/microsoft/botbuilder-dotnet/blob/main/libraries/Microsoft.Bot.Connector/ErrorResponseException.cs

If you provide your bot ID and recent timestamps of instances of this error (within 2 weeks), we can check our logs.

**Comment by luhan2017** [comment] 2023-01-19 03:26
@martinlarosa is this issue still valid? could you please provide more details for this?

**Comment by martinlarosa** [comment] 2023-01-19 15:05
Hi, it is still happening, and I'm even getting some 403s 

We'll add some more logging to try to find the real error message

**Comment by martinlarosa** [comment] 2023-01-23 18:54
> The response to the 404 should contain a code that indicates what could not be found. See https://learn.microsoft.com/en-us/microsoftteams/platform/bots/how-to/conversations/conversation-messages?tabs=dotnet#status-codes-from-bot-conversational-apis
> 
> <img alt="image" width="444" src="https://user-images.githubusercontent.com/767208/208197331-4c371731-bf75-4826-ba4a-935cab34a0d6.png">
> 
> For this POST /v3/conversations/{id}/activities endpoint, the usual reason is the referenced conversation ID has been deleted.

Regarding that, could it be that the conversation ID expires? We didn't expect that. We are actually caching the conversation ids in one of the features where we send proactive messages so that we don't hit the Graph API if we already have the value

**Comment by martinlarosa** [comment] 2023-02-20 12:58
@aosolis @luhan2017 would you comment on my previous question?

**Comment by YunnyChung** [comment] 2023-03-08 00:31
Hey @martinlarosa, to your question - 
`could it be that the conversation ID expires? We didn't expect that. We are actually caching the conversation ids in one of the features where we send proactive messages so that we don't hit the Graph API if we already have the value` 
I think most likely the thread was deleted by the user. But to really understand the root cause, I need to check logs. 

Do you still hit the same issue? If so, could you share the timestamp in UTC, bot id , tenant id and the error code?

**Comment by beauzeaux** [comment] 2023-03-08 19:36
@martinlarosa The conversations ids should not expire.

As @aosolis indicated if you can get us the _**bot id**_ and a _**timestamp**_ in the last couple of weeks (the more recent the better) we can take a look at our telemetry and get something more conclusive.

**Comment by YunnyChung** [comment] 2023-03-10 17:13
Any updates on this, @martinlarosa?

**Comment by martinlarosa** [comment] 2023-03-15 16:31
Is it really necessary to share the bot id and tenant id in a public channel?

Here's an occurrence that has just happened in UTC:
15/3/2023, 16:09:43.5809337

https://smba.trafficmanager.net/amer/v3/conversations/{someId}/activities/{someId}
Result code: 404
OperationId 71a0c935423f289582c1be0d9be85fc9

**Comment by Wajeed-msft** [comment] 2023-03-29 03:46
@martinlarosa - could you please share you Bot Id and Tenant Id to [Microsoft Teams Community Help](mailto:microsoftteamsdev@microsoft.com) alias?

**Comment by martinlarosa** [comment] 2023-03-29 23:23
Done, thank you!

**Comment by Wajeed-msft** [comment] 2023-04-05 13:58
@martinlarosa - could you please share Tenant Id as well?

**Comment by martinlarosa** [comment] 2023-04-06 13:43
I missed your email from last week. I just replied with extra information and new timestamps.

Thank you

**Comment by martinlarosa** [comment] 2023-04-25 14:24
Any news?

**Comment by luhan2017** [comment] 2023-05-08 04:28
@martinlarosa @YunnyChung , could you please follow up through email? I am going to close this ticket because it is not a real ABS issue. Please reopen if needed.

**Closed by luhan2017** 2023-05-08 04:28 UTC

**Comment by Steffi3rd** [comment] 2023-05-22 15:19
Hello guys, I have the same issue. 

Do you find a solution?

Our bot receive ConversationNotFound since this weekend whereas user still have the conversation and the user exist in the storage.

When I delete the user, I have "User Not found" (so this is normal).

The bug is ConversationNotFound whereas conversation exists for the user.

**Comment by chu-tianshu** [comment] 2023-07-17 22:38
Hi @Steffi3rd , is the issue still happening to you? Could you share more info for us to troubleshoot?

**Comment by Steffi3rd** [comment] 2023-07-20 08:10
@cts2003258 I found an alternative solution here : https://github.com/OfficeDev/TeamsFx/issues/8759#issuecomment-1561159073
